### ISSUE TITLE
Record how many people choose each answer

### ISSUE THREAD

**Issue by mgatland** [girlcodeakl/girlcode2018-term4#27]
After someone chooses an answer, show them how many people chose each answer on that question.

Example:

![](https://www.popovergenie.com/wp-content/uploads/2016/12/amazon_asks_example_1.png)

So there a few steps, This issue is for the server-side code that records the stats. We won't draw the graph.

* When they choose an answer, we need to send a message to the server saying which answer they picked *and* which question it was for.
* The server should record how many people picked each answer, so it will add 1 to a counter for the answer they chose.

- [x] Open *feed.html* in Atom
- [ ] Find the code that creates the four answer buttons

We want to make it easier to tell which answer is which. Give each of the HTML elements an attribute, like this: `data-id="0"` - give each a different value that matches the values used in the value. 

- [x] each answer button now has a `data-id` attribute

- [x] in *feed.html* find the function that is run when the user clicks on an answer button. (Look for `console.log("button clicked!")`)

We can new code after that line and it will only run when an answer button is clicked.

We need to get 2 pieces of information: the post ID and the answer number.

```javascript
let answerNumber = e.target.dataset.id;
let postIdElement = e.target.parentNode.querySelector(".postId");
let postId = postIdElement.innerHTML;
console.log("You chose post " + postId + ", answer " + answerNumber);
```
The code above puts the values you need into `postId` and `answerNumber`, and writes them in the dev tools console.

- [x] test that choosing an answer logs the post ID and answer number (0, 1, 2 or 3)

Now you need to send these values to the server. Take a look at post.html for an example of sending values to the server.

You'll create a data object, put the values you want to send into the data object, and then use the the fetch command to post it to the server.

In *post.html* we used the path "/post". Change that to "/answerChosen" so the server knows it is a new kind of request.

- [x] Use a fetch command to send a message to the server with the two pieces of information we need

> You can check what is being sent by opening your Chrome Developer Tools and looking at the network tab. There's a list of requests. Click on an answer to make a new request. It should appear at the end of the list. Click on it then look under 'headers' at the very end to see what is being sent.

# server side

- [ ] open index.js

Add this to *index.js*:

```javascript
function answerChosen(request, response) {
   console.log("Post id: " + request.body.postId);
   console.log("Answer number: " + request.body.answerNumber);
   response.send("ok");
}
app.post("/answerChosen", answerChosen);
```

The server can now reply to 'answerChosen' requests using this new function.

The server should log the values you sent through. Try it out and see if the right values come through.

- [x] the server log (in Terminal or Command Prompt) shows the same post ID and answer number as you saw in Chrome

Once you have the right values you can use them to get the appropriate post:

```javascript
let post = posts.find(x => x.id == request.body.postId);
```

Lets save the answer id into a variable with a shorter name, and convert it to a number instead of a string:

```javascript
let answerNumber = parseInt(request.body.answerNumber);
```

Record stats about who has answered the question so far:

```
if (post.answerCount === undefined) {
  post.answerCount = [0, 0, 0, 0]; //starting values
  post.totalAnswers = 0;
}
post.answerCount[answer]++; //increase counter by one
post.totalAnswers++; //increase counter by one
```

Next we have to save a copy of the post into the database. If the server is restarted, it will forget any changes it made that were not recorded in the database.

To resave the post:

```javascript
databasePosts.update({id: post.id}, post);
```

These stats are not displayed anywhere, but you can see them by looking at the raw view of the posts: `http://localhost:3000/posts`

Check that the system is recording what answers you choose. Check that the record is still correct even after restarting the server.

**Comment by jillGlass** [comment]
now records how many people choose each answer
