### ISSUE TITLE
Introduce new code style rules for the team

### ISSUE THREAD

**Issue by mgatland** [girlcodeakl/girlcode2018-term4#41]
It's easier to work as a team when we all write our code in the same style.

To make life easy, we're going to set up Atom so it automatically formats our code in a certain style. This means we don't have to worry about following the style - it's automatic.

## install Beautify

In Atom, go to Atom -> Preferences, Install

search for Atom-Beautify.

Install it!

When it's done, go to Atom -> Preferences, Packages.

Find the section for Atom-Beautify and click 'Settings.'

In the long list of settings

* go into CSS and turn on 'Beautify on Save'
* go into HTML and turn on 'Beautify on Save'
* next, go into JavaScript and turn on  'Beautify on Save'

That's your computer set up.

Test it by opening any JavaScript file and resaving it. The whole file should be rearranged into the new style.

## Now for everyone else

Go to each person on the team and set up Atom-Beautify on their computer with the same settings. Remember to turn on 'Beautify on Save' for HTML, JavaScript and CSS.

**Comment by 0lucy** [comment]
Done!
